// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Open Mobile Emulator contributors
// design-sync prebuild for Open Mobile Emulator (run from the repo root: node .design-sync/prebuild.mjs).
// The component library is the app's own source tree, so there is no library build. This script
// produces what the converter expects, all under the gitignored host/types/:
//   1. .d.ts files for the components (tsc, declaration only) so <Name>Props contracts are real;
//   2. one flat stylesheet = tokens (minus @font-face) + screens.css + app.css (minus its @import),
//      because the converter copies cssEntry verbatim and does not follow @import;
//   3. a fonts stylesheet whose @font-face urls are relative paths the converter can copy.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const host = join(root, 'host');
const out = join(host, 'types');
mkdirSync(out, { recursive: true });

// 1. Declarations. TS2688 (missing 'node'/'vite/client' type libraries) is reported but does not
//    block emission, so the exit code is ignored and the emitted files are checked instead.
try {
  execFileSync(process.execPath, [
    join(host, 'node_modules', 'typescript', 'bin', 'tsc'),
    '-p', join(here, 'tsconfig.types.json'), '--pretty', 'false',
  ], { stdio: 'pipe' });
} catch (error) {
  const text = String(error.stdout ?? '');
  const real = text.split('\n').filter((l) => /error TS/.test(l) && !/TS2688/.test(l));
  if (real.length) { console.error(real.join('\n')); process.exit(1); }
}
readFileSync(join(out, 'components', 'Button.d.ts'));

// 2. Flat component stylesheet.
const styles = join(host, 'ui', 'src', 'styles');
const read = (name) => readFileSync(join(styles, name), 'utf8').replace(/\r\n/g, '\n');
const tokens = read('tokens.css').split('\n').filter((line) => !/^@font-face\b/.test(line)).join('\n');
const app = read('app.css').replace(/^@import\s+"\.\/screens\.css";\s*$/m, '');
const flat = [
  '/* Generated by .design-sync/prebuild.mjs: tokens.css (without @font-face) + screens.css + app.css. */',
  tokens, read('screens.css'), app,
].join('\n\n');
writeFileSync(join(out, 'ome-components.css'), flat);

// 3. Fonts with relative urls (the converter copies the files into fonts/ and rewrites the rules).
const faces = read('tokens.css').split('\n').filter((line) => /^@font-face\b/.test(line))
  .map((line) => line.replace(/url\("\/fonts\//g, 'url("../ui/public/fonts/'));
writeFileSync(join(out, 'ome-fonts.css'), faces.join('\n') + '\n');
console.error(`prebuild: ${faces.length} @font-face rules, ${flat.length} bytes of CSS, declarations in host/types/`);
