# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Open Mobile Emulator contributors
[toolchain]
channel = "1.97.0"
profile = "minimal"
components = ["clippy", "rustfmt", "rust-analyzer", "rust-src"]
