// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Open Mobile Emulator contributors
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import test from 'node:test';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const capability = JSON.parse(read('app/capabilities/main.json'));
const handler = /tauri::generate_handler!\[([\s\S]*?)\]/u.exec(read('app/src/lib.rs'));
assert.ok(handler, 'The shell must register an explicit invoke handler.');
const entries = handler[1].split(',').map((entry) => entry.trim()).filter(Boolean);
const names = entries.map((entry) => {
  const command = /^commands::([a-z_]+)$/u.exec(entry);
  assert.ok(command, `Unexpected invoke handler entry: ${entry}`);
  return command[1];
});
const allowed = names.map((name) => `allow-${name.replaceAll('_', '-')}`);
const eventPermissions = ['core:event:allow-listen', 'core:event:allow-unlisten'];
// The main window has no native frame; its title bar (ui/src/components/TitleBar.tsx) drags, minimizes,
// maximizes and closes it, and reads the maximized state for the button icon. Nothing else from core:window.
const windowPermissions = [
  'core:window:allow-start-dragging',
  'core:window:allow-internal-toggle-maximize',
  'core:window:allow-minimize',
  'core:window:allow-toggle-maximize',
  'core:window:allow-close',
  'core:window:allow-is-maximized',
];
const corePermissions = [...eventPermissions, ...windowPermissions];
const literalNames = (block) => [...block.matchAll(/"([a-z_]+)"/gu)].map((match) => match[1]);

function sameNames(actual, expected) {
  assert.equal(new Set(actual).size, actual.length, 'Duplicate entries are forbidden.');
  assert.deepEqual([...actual].sort(), [...expected].sort());
}

test('all registered commands have a capability grant', () => {
  assert.ok(names.length > 0);
  assert.equal(capability.identifier, 'main');
  assert.deepEqual(capability.windows, ['main', 'overlay']);
  assert.equal(capability.remote, undefined);
  for (const permission of allowed) assert.ok(capability.permissions.includes(permission), permission);
});

test('every app grant has a registered command', () => {
  sameNames(capability.permissions.filter((permission) => permission.startsWith('allow-')), allowed);
});

test('only the event listener and title bar window permissions extend app commands', () => {
  assert.deepEqual(readdirSync(new URL('../app/capabilities/', import.meta.url)).filter((name) => name.endsWith('.json')), ['main.json']);
  sameNames(capability.permissions.filter((permission) => permission.startsWith('core:')), corePermissions);
  sameNames(capability.permissions, [...allowed, ...corePermissions]);
});

test('handler command names equal the runtime contract', () => {
  const block = /pub const TAURI_COMMANDS:[\s\S]*?=\s*&\[([\s\S]*?)\];/u.exec(read('crates/ome-runtime/src/contract.rs'));
  assert.ok(block, 'TAURI_COMMANDS must remain explicit.');
  sameNames(names, literalNames(block[1]));
});

test('the build manifest declares exactly the registered commands', () => {
  const block = /AppManifest::new\(\)\.commands\(&\[([\s\S]*?)\]\)/u.exec(read('app/build.rs'));
  assert.ok(block, 'The app manifest must enumerate its command names.');
  sameNames(literalNames(block[1]), names);
});

test('permission files are present with unchanged Tauri generator boilerplate', () => {
  for (const command of names) {
    const name = command.replaceAll('_', '-');
    const expected = `# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Open Mobile Emulator contributors
# Automatically generated - DO NOT EDIT!\n\n[[permission]]\nidentifier = "allow-${name}"\ndescription = "Enables the ${command} command without any pre-configured scope."\ncommands.allow = ["${command}"]\n\n[[permission]]\nidentifier = "deny-${name}"\ndescription = "Denies the ${command} command without any pre-configured scope."\ncommands.deny = ["${command}"]`;
    assert.equal(read(`app/permissions/autogenerated/${command}.toml`).replaceAll('\r\n', '\n').trimEnd(), expected, command);
  }
});
