// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Open Mobile Emulator contributors
#![forbid(unsafe_code)]

fn main() {
    let manifest = tauri_build::AppManifest::new().commands(&[
        "app_snapshot",
        "host_check_refresh",
        "wizard_continue",
        "wizard_skip",
        "wizard_restart",
        "whpx_enable",
        "artifact_download_start",
        "artifact_download_cancel",
        "guest_disk_create",
        "guest_start",
        "guest_stop",
        "guest_restart",
        "stage_rect_changed",
        "screenshot_save",
        "app_install_pick",
        "app_uninstall",
        "app_launch",
        "keymap_set_active",
        "keymap_set_enabled",
        "keymap_delete",
        "display_preset_apply",
        "stage_fit_set",
        "settings_save",
        "update_check",
        "update_install",
        "diagnostics_export",
        "open_logs_folder",
        "open_screenshots_folder",
        "open_registration_page",
        "guest_window_to_front",
    ]);
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(manifest))
        .expect("Tauri application configuration must be valid");
    // Tauri owns the permission body. R5 additionally requires these two lines
    // on checked-in TOML sources; retain the generator body byte for byte.
    const HEADER: &str = "# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Open Mobile Emulator contributors
";
    for entry in std::fs::read_dir("permissions/autogenerated")
        .expect("generated permission directory must exist")
    {
        let path = entry
            .expect("generated permission entry must be readable")
            .path();
        if path.extension().is_none_or(|extension| extension != "toml") {
            continue;
        }
        let source = std::fs::read_to_string(&path).expect("generated permission must exist");
        if !source.starts_with(HEADER) {
            std::fs::write(path, format!("{HEADER}{source}"))
                .expect("generated permission license header must be written");
        }
    }
}
