// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Open Mobile Emulator contributors
//! Generated scan-code names used by the keyboard interpreter and QMP key synthesizer.
//!
//! Source: <https://gitlab.com/keycodemap/keycodemapdb/-/raw/54788039c0b3486a8883090d6736c2500177af29/data/keymaps.csv>
//! Commit: `54788039c0b3486a8883090d6736c2500177af29`.
//! Source data license: BSD-3-Clause (`LICENSE.BSD` in keycodemapdb).
//!
//! Copyright (c) Individual contributors.
//! All rights reserved.
//!
//! Redistribution and use in source and binary forms, with or without modification, are permitted
//! provided that the following conditions are met:
//!
//! 1. Redistributions of source code must retain the above copyright notice, this list of
//!    conditions and the following disclaimer.
//! 2. Redistributions in binary form must reproduce the above copyright notice, this list of
//!    conditions and the following disclaimer in the documentation and/or other materials provided
//!    with the distribution.
//! 3. Neither the name of the copyright holder nor the names of its contributors may be used to
//!    endorse or promote products derived from this software without specific prior written
//!    permission.
//!
//! THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
//! IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
//! FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
//! CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//! DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
//! DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
//! IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
//! OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//!
//! The source has aliases for keypad multiply (`asterisk` and `kp_multiply`) and Print Screen
//! (`print` and `sysrq`). This generated table selects the device-specific `kp_multiply` spelling
//! and QEMU's canonical `print` spelling. Windows reports the source's `e0` prefix separately as
//! the low-level hook's extended flag.

/// Returns the QEMU `QKeyCode` name for one Windows scan-code observation.
pub fn scan_to_qcode(scan: u16, extended: bool) -> Option<&'static str> {
    match (scan, extended) {
        (0x01, false) => Some("esc"),
        (0x02, false) => Some("1"),
        (0x03, false) => Some("2"),
        (0x04, false) => Some("3"),
        (0x05, false) => Some("4"),
        (0x06, false) => Some("5"),
        (0x07, false) => Some("6"),
        (0x08, false) => Some("7"),
        (0x09, false) => Some("8"),
        (0x0a, false) => Some("9"),
        (0x0b, false) => Some("0"),
        (0x0c, false) => Some("minus"),
        (0x0d, false) => Some("equal"),
        (0x0e, false) => Some("backspace"),
        (0x0f, false) => Some("tab"),
        (0x10, false) => Some("q"),
        (0x11, false) => Some("w"),
        (0x12, false) => Some("e"),
        (0x13, false) => Some("r"),
        (0x14, false) => Some("t"),
        (0x15, false) => Some("y"),
        (0x16, false) => Some("u"),
        (0x17, false) => Some("i"),
        (0x18, false) => Some("o"),
        (0x19, false) => Some("p"),
        (0x1a, false) => Some("bracket_left"),
        (0x1b, false) => Some("bracket_right"),
        (0x1c, false) => Some("ret"),
        (0x1d, false) => Some("ctrl"),
        (0x1e, false) => Some("a"),
        (0x1f, false) => Some("s"),
        (0x20, false) => Some("d"),
        (0x21, false) => Some("f"),
        (0x22, false) => Some("g"),
        (0x23, false) => Some("h"),
        (0x24, false) => Some("j"),
        (0x25, false) => Some("k"),
        (0x26, false) => Some("l"),
        (0x27, false) => Some("semicolon"),
        (0x28, false) => Some("apostrophe"),
        (0x29, false) => Some("grave_accent"),
        (0x2a, false) => Some("shift"),
        (0x2b, false) => Some("backslash"),
        (0x2c, false) => Some("z"),
        (0x2d, false) => Some("x"),
        (0x2e, false) => Some("c"),
        (0x2f, false) => Some("v"),
        (0x30, false) => Some("b"),
        (0x31, false) => Some("n"),
        (0x32, false) => Some("m"),
        (0x33, false) => Some("comma"),
        (0x34, false) => Some("dot"),
        (0x35, false) => Some("slash"),
        (0x36, false) => Some("shift_r"),
        (0x37, false) => Some("kp_multiply"),
        (0x38, false) => Some("alt"),
        (0x39, false) => Some("spc"),
        (0x3a, false) => Some("caps_lock"),
        (0x3b, false) => Some("f1"),
        (0x3c, false) => Some("f2"),
        (0x3d, false) => Some("f3"),
        (0x3e, false) => Some("f4"),
        (0x3f, false) => Some("f5"),
        (0x40, false) => Some("f6"),
        (0x41, false) => Some("f7"),
        (0x42, false) => Some("f8"),
        (0x43, false) => Some("f9"),
        (0x44, false) => Some("f10"),
        (0x45, false) => Some("num_lock"),
        (0x46, false) => Some("scroll_lock"),
        (0x47, false) => Some("kp_7"),
        (0x48, false) => Some("kp_8"),
        (0x49, false) => Some("kp_9"),
        (0x4a, false) => Some("kp_subtract"),
        (0x4b, false) => Some("kp_4"),
        (0x4c, false) => Some("kp_5"),
        (0x4d, false) => Some("kp_6"),
        (0x4e, false) => Some("kp_add"),
        (0x4f, false) => Some("kp_1"),
        (0x50, false) => Some("kp_2"),
        (0x51, false) => Some("kp_3"),
        (0x52, false) => Some("kp_0"),
        (0x53, false) => Some("kp_decimal"),
        (0x54, false) => Some("print"),
        (0x55, false) => Some("f16"),
        (0x56, false) => Some("less"),
        (0x57, false) => Some("f11"),
        (0x58, false) => Some("f12"),
        (0x59, false) => Some("kp_equals"),
        (0x5a, false) => Some("f20"),
        (0x5b, false) => Some("lf"),
        (0x5d, false) => Some("f13"),
        (0x5e, false) => Some("f14"),
        (0x5f, false) => Some("f15"),
        (0x64, false) => Some("open"),
        (0x65, false) => Some("paste"),
        (0x6d, false) => Some("f23"),
        (0x6f, false) => Some("f24"),
        (0x70, false) => Some("katakanahiragana"),
        (0x73, false) => Some("ro"),
        (0x74, false) => Some("f21"),
        (0x77, false) => Some("hiragana"),
        (0x79, false) => Some("henkan"),
        (0x7b, false) => Some("muhenkan"),
        (0x7d, false) => Some("yen"),
        (0x7e, false) => Some("kp_comma"),
        (0xf1, false) => Some("lang2"),
        (0xf2, false) => Some("lang1"),
        (0x03, true) => Some("f17"),
        (0x04, true) => Some("f19"),
        (0x05, true) => Some("again"),
        (0x06, true) => Some("props"),
        (0x07, true) => Some("undo"),
        (0x0c, true) => Some("front"),
        (0x10, true) => Some("audioprev"),
        (0x19, true) => Some("audionext"),
        (0x1c, true) => Some("kp_enter"),
        (0x1d, true) => Some("ctrl_r"),
        (0x1e, true) => Some("menu"),
        (0x20, true) => Some("audiomute"),
        (0x21, true) => Some("calculator"),
        (0x22, true) => Some("audioplay"),
        (0x24, true) => Some("audiostop"),
        (0x2e, true) => Some("volumedown"),
        (0x30, true) => Some("volumeup"),
        (0x32, true) => Some("ac_home"),
        (0x35, true) => Some("kp_divide"),
        (0x38, true) => Some("alt_r"),
        (0x3c, true) => Some("cut"),
        (0x41, true) => Some("find"),
        (0x46, true) => Some("pause"),
        (0x47, true) => Some("home"),
        (0x48, true) => Some("up"),
        (0x49, true) => Some("pgup"),
        (0x4b, true) => Some("left"),
        (0x4d, true) => Some("right"),
        (0x4f, true) => Some("end"),
        (0x50, true) => Some("down"),
        (0x51, true) => Some("pgdn"),
        (0x52, true) => Some("insert"),
        (0x53, true) => Some("delete"),
        (0x5b, true) => Some("meta_l"),
        (0x5c, true) => Some("meta_r"),
        (0x5d, true) => Some("compose"),
        (0x5e, true) => Some("power"),
        (0x5f, true) => Some("sleep"),
        (0x63, true) => Some("wake"),
        (0x66, true) => Some("ac_bookmarks"),
        (0x67, true) => Some("ac_refresh"),
        (0x68, true) => Some("stop"),
        (0x69, true) => Some("ac_forward"),
        (0x6a, true) => Some("ac_back"),
        (0x6b, true) => Some("computer"),
        (0x6c, true) => Some("mail"),
        (0x6d, true) => Some("mediaselect"),
        (0x75, true) => Some("help"),
        (0x77, true) => Some("f18"),
        (0x78, true) => Some("copy"),
        (0x79, true) => Some("f22"),
        _ => None,
    }
}

/// Returns the W3C `KeyboardEvent.code` name for one Windows scan-code observation.
pub fn scan_to_browser_code(scan: u16, extended: bool) -> Option<&'static str> {
    match (scan, extended) {
        (0x01, false) => Some("Escape"),
        (0x02, false) => Some("Digit1"),
        (0x03, false) => Some("Digit2"),
        (0x04, false) => Some("Digit3"),
        (0x05, false) => Some("Digit4"),
        (0x06, false) => Some("Digit5"),
        (0x07, false) => Some("Digit6"),
        (0x08, false) => Some("Digit7"),
        (0x09, false) => Some("Digit8"),
        (0x0a, false) => Some("Digit9"),
        (0x0b, false) => Some("Digit0"),
        (0x0c, false) => Some("Minus"),
        (0x0d, false) => Some("Equal"),
        (0x0e, false) => Some("Backspace"),
        (0x0f, false) => Some("Tab"),
        (0x10, false) => Some("KeyQ"),
        (0x11, false) => Some("KeyW"),
        (0x12, false) => Some("KeyE"),
        (0x13, false) => Some("KeyR"),
        (0x14, false) => Some("KeyT"),
        (0x15, false) => Some("KeyY"),
        (0x16, false) => Some("KeyU"),
        (0x17, false) => Some("KeyI"),
        (0x18, false) => Some("KeyO"),
        (0x19, false) => Some("KeyP"),
        (0x1a, false) => Some("BracketLeft"),
        (0x1b, false) => Some("BracketRight"),
        (0x1c, false) => Some("Enter"),
        (0x1d, false) => Some("ControlLeft"),
        (0x1e, false) => Some("KeyA"),
        (0x1f, false) => Some("KeyS"),
        (0x20, false) => Some("KeyD"),
        (0x21, false) => Some("KeyF"),
        (0x22, false) => Some("KeyG"),
        (0x23, false) => Some("KeyH"),
        (0x24, false) => Some("KeyJ"),
        (0x25, false) => Some("KeyK"),
        (0x26, false) => Some("KeyL"),
        (0x27, false) => Some("Semicolon"),
        (0x28, false) => Some("Quote"),
        (0x29, false) => Some("Backquote"),
        (0x2a, false) => Some("ShiftLeft"),
        (0x2b, false) => Some("Backslash"),
        (0x2c, false) => Some("KeyZ"),
        (0x2d, false) => Some("KeyX"),
        (0x2e, false) => Some("KeyC"),
        (0x2f, false) => Some("KeyV"),
        (0x30, false) => Some("KeyB"),
        (0x31, false) => Some("KeyN"),
        (0x32, false) => Some("KeyM"),
        (0x33, false) => Some("Comma"),
        (0x34, false) => Some("Period"),
        (0x35, false) => Some("Slash"),
        (0x36, false) => Some("ShiftRight"),
        (0x37, false) => Some("NumpadMultiply"),
        (0x38, false) => Some("AltLeft"),
        (0x39, false) => Some("Space"),
        (0x3a, false) => Some("CapsLock"),
        (0x3b, false) => Some("F1"),
        (0x3c, false) => Some("F2"),
        (0x3d, false) => Some("F3"),
        (0x3e, false) => Some("F4"),
        (0x3f, false) => Some("F5"),
        (0x40, false) => Some("F6"),
        (0x41, false) => Some("F7"),
        (0x42, false) => Some("F8"),
        (0x43, false) => Some("F9"),
        (0x44, false) => Some("F10"),
        (0x45, false) => Some("NumLock"),
        (0x46, false) => Some("ScrollLock"),
        (0x47, false) => Some("Numpad7"),
        (0x48, false) => Some("Numpad8"),
        (0x49, false) => Some("Numpad9"),
        (0x4a, false) => Some("NumpadSubtract"),
        (0x4b, false) => Some("Numpad4"),
        (0x4c, false) => Some("Numpad5"),
        (0x4d, false) => Some("Numpad6"),
        (0x4e, false) => Some("NumpadAdd"),
        (0x4f, false) => Some("Numpad1"),
        (0x50, false) => Some("Numpad2"),
        (0x51, false) => Some("Numpad3"),
        (0x52, false) => Some("Numpad0"),
        (0x53, false) => Some("NumpadDecimal"),
        (0x54, false) => Some("PrintScreen"),
        (0x55, false) => Some("F16"),
        (0x56, false) => Some("IntlBackslash"),
        (0x57, false) => Some("F11"),
        (0x58, false) => Some("F12"),
        (0x59, false) => Some("NumpadEqual"),
        (0x5a, false) => Some("F20"),
        (0x5d, false) => Some("F13"),
        (0x5e, false) => Some("F14"),
        (0x5f, false) => Some("F15"),
        (0x64, false) => Some("Open"),
        (0x65, false) => Some("Paste"),
        (0x6d, false) => Some("F23"),
        (0x6f, false) => Some("F24"),
        (0x70, false) => Some("KanaMode"),
        (0x73, false) => Some("IntlRo"),
        (0x74, false) => Some("F21"),
        (0x76, false) => Some("Lang5"),
        (0x77, false) => Some("Hiragana"),
        (0x78, false) => Some("Katakana"),
        (0x79, false) => Some("Convert"),
        (0x7b, false) => Some("NonConvert"),
        (0x7d, false) => Some("IntlYen"),
        (0x7e, false) => Some("NumpadComma"),
        (0xf1, false) => Some("Lang2"),
        (0xf2, false) => Some("Lang1"),
        (0x03, true) => Some("F17"),
        (0x04, true) => Some("F19"),
        (0x05, true) => Some("Again"),
        (0x06, true) => Some("Props"),
        (0x07, true) => Some("Undo"),
        (0x10, true) => Some("MediaTrackPrevious"),
        (0x19, true) => Some("MediaTrackNext"),
        (0x1c, true) => Some("NumpadEnter"),
        (0x1d, true) => Some("ControlRight"),
        (0x20, true) => Some("AudioVolumeMute"),
        (0x21, true) => Some("LaunchApp2"),
        (0x22, true) => Some("MediaPlayPause"),
        (0x24, true) => Some("MediaStop"),
        (0x25, true) => Some("Suspend"),
        (0x2e, true) => Some("AudioVolumeDown"),
        (0x30, true) => Some("AudioVolumeUp"),
        (0x32, true) => Some("BrowserHome"),
        (0x35, true) => Some("NumpadDivide"),
        (0x38, true) => Some("AltRight"),
        (0x3c, true) => Some("Cut"),
        (0x41, true) => Some("Find"),
        (0x46, true) => Some("Pause"),
        (0x47, true) => Some("Home"),
        (0x48, true) => Some("ArrowUp"),
        (0x49, true) => Some("PageUp"),
        (0x4b, true) => Some("ArrowLeft"),
        (0x4d, true) => Some("ArrowRight"),
        (0x4f, true) => Some("End"),
        (0x50, true) => Some("ArrowDown"),
        (0x51, true) => Some("PageDown"),
        (0x52, true) => Some("Insert"),
        (0x53, true) => Some("Delete"),
        (0x5b, true) => Some("MetaLeft"),
        (0x5c, true) => Some("MetaRight"),
        (0x5d, true) => Some("ContextMenu"),
        (0x5e, true) => Some("Power"),
        (0x5f, true) => Some("Sleep"),
        (0x63, true) => Some("WakeUp"),
        (0x65, true) => Some("BrowserSearch"),
        (0x66, true) => Some("BrowserFavorites"),
        (0x67, true) => Some("BrowserRefresh"),
        (0x68, true) => Some("BrowserStop"),
        (0x69, true) => Some("BrowserForward"),
        (0x6a, true) => Some("BrowserBack"),
        (0x6b, true) => Some("LaunchApp1"),
        (0x6c, true) => Some("LaunchMail"),
        (0x6d, true) => Some("MediaSelect"),
        (0x75, true) => Some("Help"),
        (0x76, true) => Some("NumpadParenLeft"),
        (0x77, true) => Some("F18"),
        (0x78, true) => Some("Copy"),
        (0x79, true) => Some("F22"),
        (0x7b, true) => Some("NumpadParenRight"),
        (0x7d, true) => Some("Eject"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn distinguishes_main_and_extended_keys_with_the_same_scan_byte() {
        assert_eq!(scan_to_qcode(0x1c, false), Some("ret"));
        assert_eq!(scan_to_qcode(0x1c, true), Some("kp_enter"));
        assert_eq!(scan_to_browser_code(0x1c, false), Some("Enter"));
        assert_eq!(scan_to_browser_code(0x1c, true), Some("NumpadEnter"));
        assert_eq!(scan_to_qcode(0x48, false), Some("kp_8"));
        assert_eq!(scan_to_qcode(0x48, true), Some("up"));
    }

    #[test]
    fn maps_the_real_check_and_suspend_keys() {
        assert_eq!(scan_to_qcode(0x1e, false), Some("a"));
        assert_eq!(scan_to_browser_code(0x1e, false), Some("KeyA"));
        assert_eq!(scan_to_qcode(0x58, false), Some("f12"));
        assert_eq!(scan_to_browser_code(0x58, false), Some("F12"));
    }

    #[test]
    fn leaves_unknown_scan_codes_unmapped() {
        assert_eq!(scan_to_qcode(0xffff, false), None);
        assert_eq!(scan_to_browser_code(0xffff, true), None);
    }
}
